// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function $$default(param) {
  return React.createElement("div", undefined, "Hello from ReScript and Next.js");
}

exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
