// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function $$default(props) {
  return React.createElement("div", {
              style: {
                border: "solid 1px red"
              }
            }, React.createElement(props.Component, props.pageProps));
}

exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
